GET http://localhost:3003/api/forecast/35.75-281.25
###

DELETE http://localhost:3003/api/charts/testName.png
###

GET http://localhost:3003/api/search?location=raleigh
###

GET http://localhost:3003/api/search?lat=35.898016&lon=-78.734063
###

GET http://localhost:3003/api/search?lat=36.0000&lon=-78.7500
###

GET http://localhost:3003/api/search?lat=0&lon=0
###

GET http://localhost:3003/api/search?location=aldkfjvnowiejlsd
###

GET http://localhost:3003/api/forecast?id=

